import Phaser from 'phaser';
import type {LevelDefinition,TimedHazardDefinition} from '../types/game';
import {addSpikes} from '../objects/Hazard'; import {timedCycleState} from './TimedCycle'; import {MovingPlatform} from '../objects/MovingPlatform'; import {FallingPlatform} from '../objects/FallingPlatform'; import {LaserGate} from '../objects/LaserGate'; import {ExitDoor} from '../objects/ExitDoor';
export interface BuiltLevel{platforms:Phaser.Physics.Arcade.StaticGroup;hazards:Phaser.Physics.Arcade.StaticGroup;moving:MovingPlatform[];falling:FallingPlatform[];lasers:LaserGate[];timedZones:TimedZone[];forceZones:ForceZone[];conveyors:ConveyorZone[];door:ExitDoor;objects:number}
export class TimedZone{readonly zone:Phaser.GameObjects.Zone;private readonly visual:Phaser.GameObjects.Rectangle;constructor(scene:Phaser.Scene,private readonly definition:TimedHazardDefinition,color:number){this.visual=scene.add.rectangle(definition.x,definition.y,definition.width,definition.height??30,color,.15).setDepth(10);this.zone=scene.add.zone(definition.x,definition.y,definition.width,definition.height??30);scene.physics.add.existing(this.zone,true);(this.zone.body as Phaser.Physics.Arcade.StaticBody).enable=false;}update(time:number):void{const state=timedCycleState(time,this.definition.activeMs,this.definition.inactiveMs,this.definition.warningMs,this.definition.phaseMs);const next=state==='active';(this.zone.body as Phaser.Physics.Arcade.StaticBody).enable=next;const warning=state==='warning';this.visual.setAlpha(next ? .75 : warning ? .35 : .12).setStrokeStyle(warning?3:1,0xffffff,warning ? .9 : .3);}}
export class ForceZone{readonly zone:Phaser.GameObjects.Zone;constructor(scene:Phaser.Scene,readonly forceX:number,readonly forceY:number,x:number,y:number,width:number,height:number){this.zone=scene.add.zone(x,y,width,height);scene.physics.add.existing(this.zone,true);for(let i=0;i<5;i+=1)scene.add.text(x-width/2+i*width/5,y,forceY<0?'↑':forceX<0?'←':'→',{fontFamily:'monospace',fontSize:'22px',color:'#bcecff'}).setAlpha(.45);}}
export class ConveyorZone{readonly zone:Phaser.GameObjects.Zone;constructor(scene:Phaser.Scene,readonly speed:number,x:number,y:number,width:number,height:number){this.zone=scene.add.zone(x,y,width,height);scene.physics.add.existing(this.zone,true);scene.add.tileSprite(x,y,width,height,'moving-platform').setTint(speed>0?0x77f29a:0xff9c4a).setDepth(5);}}
export class LevelFactory{constructor(private readonly scene:Phaser.Scene){}build(level:LevelDefinition):BuiltLevel{const platforms=this.scene.physics.add.staticGroup();for(const p of level.platforms){const sprite=platforms.create(p.x,p.y,p.style==='warning'?'platform-warning':p.style==='wall'?'wall':'platform') as Phaser.Physics.Arcade.Sprite;sprite.setDisplaySize(p.width,p.height??24).refreshBody();if(p.oneWay)(sprite.body as Phaser.Physics.Arcade.StaticBody).checkCollision.down=false;}
const hazards=this.scene.physics.add.staticGroup();for(const spike of level.spikes)addSpikes(hazards,spike.x,spike.y,spike.width);const moving=level.movingPlatforms.map(d=>new MovingPlatform(this.scene,d));const falling=level.fallingPlatforms.map(d=>new FallingPlatform(this.scene,d));const lasers=level.lasers.map(d=>new LaserGate(this.scene,d));const timedZones=level.electricZones.map(d=>new TimedZone(this.scene,d,0x5ef1ff));const forceZones=level.fans.map(d=>new ForceZone(this.scene,d.forceX,d.forceY,d.x,d.y,d.width,d.height??100));const conveyors=level.conveyors.map(d=>new ConveyorZone(this.scene,d.speed,d.x,d.y,d.width,d.height??28));for(const t of level.tutorials)this.scene.add.text(t.x,t.y,t.text,{fontFamily:'monospace',fontSize:'14px',color:'#d9e7ed',backgroundColor:'#101820aa',padding:{x:8,y:5}}).setDepth(30);const door=new ExitDoor(this.scene,level.exit.x,level.exit.y);return{platforms,hazards,moving,falling,lasers,timedZones,forceZones,conveyors,door,objects:platforms.getLength()+hazards.getLength()+moving.length+falling.length+lasers.length};}}
