import Phaser from 'phaser';
import type { ResultData } from '../types/game';
import { LEVELS } from '../config/levelConfig';
import { StorageService, type CompletionOutcome } from '../services/StorageService';
import { calculateRank, seconds } from '../systems/Statistics';
import { InputManager } from '../input/InputManager';
import { InputAction } from '../input/InputAction';
import { createFloorRunData } from '../runs/RunContext';
import { ScreenShell, UiFocusController, UiTypography, type UiButtonHandle } from '../ui/UiKit';
import { ToastController } from '../ui/Toast';
type ResultAction='next'|'retry'|'floors'|'menu';
export class ResultsScene extends Phaser.Scene {
  private manager!:InputManager;private resultData!:ResultData;private outcome!:CompletionOutcome;private actions:UiButtonHandle[]=[];private selected=0;private focus!:UiFocusController;private toast!:ToastController;
  constructor(){super('Results');}
  create(data:ResultData):void{const shell=new ScreenShell(this,'RESULTADOS','Revisá tu tiempo y elegí qué hacer a continuación.');const level=LEVELS[data.levelIndex];if(!level)throw new Error('Invalid result level');this.resultData=data;const rank=calculateRank(level,data.elapsedMs,data.deaths);this.outcome=new StorageService().completeFloor(data.floor,data.elapsedMs,data.deaths,rank,data.splits,data.segments,data.eligibility,data.ghostRun);this.manager=new InputManager(this,this.outcome.save.input);this.manager.blockInherited();this.toast=new ToastController(this);const best=this.outcome.save.floors[String(data.floor)];shell.panel(40,112,420,172,'main-result');shell.panel(476,112,444,172,'progress');shell.panel(40,300,880,150,'actions');this.add.text(64,132,`RESULTADO PRINCIPAL\n\nTIEMPO  ${seconds(data.elapsedMs)} s\nRANGO   ${rank}\nPB      ${seconds(best?.bestTimeMs??data.elapsedMs)} s\nDELTA   ${this.outcome.newBestTime?'NUEVO PB':'SIN CAMBIOS'}`,UiTypography(16));this.add.text(500,132,`PROGRESO\n\nSPLITS  ${Object.keys(data.splits).length}/${level.splits.length}\nSEGMENTOS MEJORADOS  ${this.outcome.improvedSegments.length}\nMEJOR TEÓRICO  ${this.outcome.bestTheoreticalMs?`${seconds(this.outcome.bestTheoreticalMs)} s`:'--'}\nFANTASMA  ${this.outcome.ghostSaved?'GUARDADO':'SIN CAMBIOS'}\nPISO DESBLOQUEADO  ${this.outcome.newlyUnlockedFloor??'--'}`,UiTypography(16));const definitions:{id:ResultAction;label:string}[]=[];const next=LEVELS.find(candidate=>candidate.floor===data.floor+1);if(next&&!data.final&&data.mode==='competitive')definitions.push({id:'next',label:`IR A ${next.name}`});definitions.push({id:'retry',label:'REPETIR'},{id:'floors',label:'VOLVER A PISOS'},{id:'menu',label:'MENÚ'});this.actions=definitions.map((action,i)=>shell.button(`result-${action.id}`,action.label,64+(i%2)*420,316+Math.floor(i/2)*58,396,()=>this.activate(action.id),{primary:i===0,parent:'actions'}));this.focus=new UiFocusController(shell,this.actions);if(!this.outcome.persisted)this.toast.show('EL PROGRESO CAMBIÓ, PERO NO PUDO GUARDARSE','warning',5000);this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>{this.focus.destroy();this.toast.destroy();this.manager.destroy();});}
  update():void{this.manager.poll();if(this.manager.wasPressed(InputAction.MENU_UP)||this.manager.wasPressed(InputAction.MENU_LEFT)){this.selected=(this.selected+this.actions.length-1)%this.actions.length;this.paint();}if(this.manager.wasPressed(InputAction.MENU_DOWN)||this.manager.wasPressed(InputAction.MENU_RIGHT)){this.selected=(this.selected+1)%this.actions.length;this.paint();}if(this.manager.wasPressed(InputAction.CONFIRM))this.actions[this.selected]?.bg.emit('pointerdown');if(this.manager.wasPressed(InputAction.RESTART))this.activate('retry');if(this.manager.wasPressed(InputAction.BACK))this.activate('floors');}
  private paint():void{this.actions.forEach((x,i)=>x.setFocused(i===this.selected));}
  private activate(action:ResultAction):void{if(action==='retry')this.scene.start('Level',{...this.resultData.context});else if(action==='floors')this.scene.start('FloorSelect');else if(action==='menu')this.scene.start('Menu');else{const next=LEVELS.find(level=>level.floor===this.resultData.floor+1);if(next)this.scene.start('Level',createFloorRunData(LEVELS.indexOf(next),'competitive'));}}
}
