import fs from 'node:fs';
const read = file => fs.readFileSync(file, 'utf8');
const tokens = read('src/ui/UiTokens.ts');
for (const token of ['background','elevated','panel','selected','border','focus','text','secondary','disabled','primary','warning','danger','success']) if (!new RegExp(`\\b${token}:`).test(tokens)) throw new Error(`Token ausente: ${token}`);
if (!/hitHeight:\s*44/.test(tokens) || !/safe:\s*24/.test(tokens)) throw new Error('Mínimos UI inválidos.');
const kit = read('src/ui/UiKit.ts');
for (const contract of ['ScreenShell','UiFocusController','button(','toggle(','slider(','tabs(','badge(','destroy()']) if (!kit.includes(contract)) throw new Error(`UiKit sin ${contract}`);
const settings = read('src/scenes/SettingsScene.ts');
for (const copy of ["type SettingsCategory","id: 'audio'","id: 'accessibility'","id: 'gameplay'","id: 'controls'","id: 'local-data'",'ZONA DE PELIGRO']) if (!settings.includes(copy)) throw new Error(`Ajustes sin contrato ${copy}`);
if (/Navegación accesible · foco visible/.test(settings)) throw new Error('Subtítulo decorativo en Ajustes.');
const controls=read('src/scenes/ControlsScene.ts');
for(const copy of ["'TECLADO'","'MANDO'",'ZONA MUERTA','GENÉRICO','CAMBIAR “']) if(!controls.includes(copy))throw new Error(`Controles sin ${copy}`);
const floor=read('src/scenes/FloorSelectScene.ts'); if(floor.includes('🔒')||/select\([^)]*\)[\s\S]{0,500}new StorageService/.test(floor))throw new Error('FloorSelect usa emoji o carga por foco.');
const results=read('src/scenes/ResultsScene.ts'); if(results.includes('levelIndex + 1')||results.includes('data.floor === 2'))throw new Error('Results usa navegación especial por índice.');
if(!read('index.html').includes('<title>One More Floor</title>'))throw new Error('Título del navegador inválido.');
console.log('UI estática v1.1.2: contratos, copy y autoridades verificados.');
